name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make clbuttic better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area does this affect?
      options:
        - Word lists
        - New language support
        - Tooling/scripts
        - Documentation
        - Package distribution
        - Other
    validations:
      required: true
